src/pharmpy/tools/resmod/tool.py

Hi, the request is about changing the best model selection criteria in resmod. Because in this case, the "dofv" is always negative and we need to select the lowest one.

Change the best model selection criteria

---

src/pharmpy/tools/resmod/tool.py

Hi Rikard,
I am so sorry that I make a mistake on iiv_on_ruv model name. I forgot we use different names in `_create_iiv_on_ruv_model` and the result data frame. Here must be the capital letters as we used in the result data frame, otherwise, it will select the wrong model. I upgrade the pharmpy package to try the new resmod with some dataset and find this problem...I am very sorry!

Correct the iiv_on_ruv model name for best model selection.

---

src/pharmpy/tools/resmod/tool.py

Hi Rikard,
Mats suggested using p=0.01 instead of p=0.05 as the selection criteria for resmod models, so I changed the cutoff in resmod.
Best regards,
Zhe Huang

Change best model selection criteria with p=0.01 in resmod

---

src/pharmpy/statements.py
tests/test_statements.py

`direct_dependencies` will give a list of statements that are the closest dependencies of a certain statement. Added this method to not expose the networkx dependency graph. Also added the possibility to give a statement as input to `dependencies`

Add direct_dependencies method and improve dependencies

---

src/pharmpy/tools/resmod/tool.py

Hi Rikard,
This PR is to fix an issue in `create_best_model `function when transforming time varying model. because the resmod dataset and nlme model dataset are different, I should use the tad column in resmod dataset rather than tad column in the original dataset when I transform the best model.
Best regards,
Zhe Huang

Use the same time varying cutoff for resmod models and best model

---

src/pharmpy/modeling/amd.py
src/pharmpy/tools/resmod/tool.py

Hi Rikard,
I change the commit message so I close the previous PR and open a new one. I use the same cutoff for CWRES model comparison and full model comparison. If there is no significant difference between the start model and the best model generated by resmod, the best model will be the start model and the selected_model_name will be called 'base' so that we can stop the iteration in amd when the model name is 'base'.
Best regards,
Zhe Huang

Compare full models in resmod and avoid unnecessary iteration in amd

---

src/pharmpy/plugins/nlmixr/model.py
src/pharmpy/plugins/nonmem/run.py
src/pharmpy/workflows/model_database/baseclass.py
src/pharmpy/workflows/model_database/local_directory.py
src/pharmpy/workflows/model_database/null_database.py

[refactor] Model plugin run metadata v0

---

src/pharmpy/lock.py
src/pharmpy/modeling/common.py
src/pharmpy/plugins/nlmixr/model.py
src/pharmpy/plugins/nonmem/run.py
src/pharmpy/workflows/model_database/baseclass.py
src/pharmpy/workflows/model_database/local_directory.py
src/pharmpy/workflows/model_database/null_database.py
tests/execute/test_database.py
tests/integration/test_amd.py
tests/integration/test_estmethod.py
tests/integration/test_fit.py
tests/integration/test_iiv.py
tests/integration/test_modelsearch.py

The goal is to have a generic way to do atomic reads and writes on the different databases.
**TODO**:
- @rikardn I think there are some issues where reading the `modelfit_results` attribute inside any of the database methods may cause locking recursion. We should be able to detect if this happens by using nonreentrant thread locks.
**DONE**:
Some links in the wild:
- https://www.oreilly.com/library/view/python-cookbook/0596001673/ch04s25.html
- https://github.com/harlowja/fasteners
- https://github.com/WoLpH/portalocker/blob/00cffcb1831208691d3bf6850df4768989a0bd4c/portalocker/portalocker.py
- https://docs.openstack.org/pylockfile/latest/

[refactor] Database transactions v0

---

src/pharmpy/datainfo.py
src/pharmpy/modeling/data.py
src/pharmpy/modeling/example_models/pheno.datainfo
src/pharmpy/tools/amd/funcs.py
tests/integration/test_amd.py
tests/testdata/nonmem/pheno.datainfo
tests/tools/test_start_model.py

Hi Rikard,
Here is the commit for removing the default separator,  @pharmpy-dev-123 and I found that we should put double backslash before the` s+` in the datainfo file for the white space separator, only one backslash doesn't work. 
Best regard,
Zhe Huang

Add separator in datainfo file and read in dataset correctly

---

src/pharmpy/plugins/nonmem/records/code_record.py
src/pharmpy/plugins/nonmem/update.py

> :warning: Needs commit editing. @rikardn Ready for review.
In this PR we use children index ranges to locate statement nodes in the AST. It is lighter on reference counting and avoids the linear scan to align the children array with the statement nodes array.

[refactor] Simplified and more lightweight implementation of CodeRecord#statements

---

docs/_ext/conversion.py
docs/_ext/pharmpy_snippet.py
docs/bootstrap.rst
docs/cdd.rst
docs/conf.py
docs/crossval.rst
docs/custom.css
docs/data.rst
docs/frem.rst
docs/iivsearch.rst
docs/linearize.rst
docs/model.rst
docs/modelfit.rst
docs/modeling.rst
docs/modelsearch.rst
docs/nonmem_plugin.rst
docs/qa.rst
docs/requirements.txt
docs/resmod.rst
docs/scm.rst
docs/simeval.rst

[docs] Automation of R examples for web documentation

---

src/pharmpy/lock.py
src/pharmpy/model.py
src/pharmpy/modeling/iiv_on_ruv.py
src/pharmpy/plugins/nlmixr/model.py
src/pharmpy/plugins/nonmem/model.py
src/pharmpy/plugins/nonmem/results.py
src/pharmpy/plugins/nonmem/run.py
src/pharmpy/workflows/model_database/local_directory.py
tests/integration/test_modelsearch.py
tests/nonmem/test_nonmem_model.py
tests/tools/test_frem.py

This PR also fixes a bug in the implementation of non-blocking thread-level locks. This should have no consequences since those are not used yet. I just realized there was a problem there while debugging this deadlock. Could be made a separate PR but I do not think this is necessary.

[fix] Avoid model database deadlock on Windows because of implicit recursive calls to the database in `modelfit_results` and others

---

tests/integration/test_resmod.py

Hi Rikard, 
This PR is to give an example to let resmod iterate twice in test. I think it can also be applied as the example of documentation.  I remove the covariance step and delete the TAD statement. It looks not very decent because of the large p-value but it is the easiest choice so far.
Best regards,
Zhe Huang

Resmod example

---

src/pharmpy/modeling/amd.py

Hi Rikard,
This PR is a very basic version of adding the model object as the input of AMD function. There are also some things I am not very sure about:
My understanding is if we want to use the model object as the starting point, we should have a pharmpy model or do `model=read_model(path)`, then we do `run_amd(model, ...)`. The benefit is the flexibility of input, `run_amd` can follow some functions which return a model object (I think?). But this is just my intuitive feeling.
Another possibility to deal with it is to give a path of the mod file and let the AMD function handle different situations. For example, we can have `path= '~/xxx.mod' ` or `path= '~/xxx.csv'` and we convert model inside our AMD function. 
Which one do you think is more user-friendly?
Best regards,
Zhe Huang

Add model object as input of amd function

---

src/pharmpy/modeling/covariate_effect.py
tests/modeling/test_modeling.py

> @stellabelin @rikardn Ready for review.

[fix] Fix composition of `add_covariate_effect` calls

---

src/pharmpy/modeling/amd.py

Hi Rikard, 
This PR is to concatenate the results of modelsearch, iivsearch and resmod. I didn't write the AMD test because I was not sure it will still lead to some issues or not. But I think we need to check what the tables look like, I printed them, and here are the results:  
The way I concatenated the subtables is not very decent, it looks foolish...I did many tries today and this is the only way that works for me. I guess there might be a clear way which I didn't find online. I reset each subtable's index before concatenation because iivsearch has tuple multiIndex: step & model and` pd.concat(df, keys=keys)`  doesn't work in this situation. I also want to split the tuple and make the step a column so that I can fill numbers in it for other subtools. But after reset the index, it …

AMD results first version

---

src/pharmpy/modeling/amd.py

Hi Rikard,
This PR is to add the summary_errors on the final selected model as we discussed just now.
Best regards,
Zhe Huang

Add summary_errors table for final model only

---

docs/custom.css

Fallback to default background-color in pharmpy snippets.

[docs] Improve CSS for Pharmpy code snippets in dark mode

---

src/pharmpy/plugins/nonmem/advan.py
src/pharmpy/plugins/nonmem/model.py
src/pharmpy/tools/amd/funcs.py
tests/tools/test_start_model.py

Hi both,
@pharmpy-dev-123 and I found the issue was made by `nonmem.plugin.model.convert_model()`. Because we need to use the dataset to change the model statements (dose type: bolus to infusion), but the path is not correct: `file.csv`. So we need to set the correct path before we change the statement. Then another issue pops out:
```
Traceback (most recent call last):
Input In [5] in <cell line: 4>
run_amd('C:\\Users\\zhehu311\\Desktop\\debug\\amd\\xuanlin\\dauno_filtered.csv',
File ~\Anaconda3\lib\site-packages\pharmpy\tools\run_amd.py:102 in run_amd
model = convert_model(model, 'nonmem')  # FIXME: Workaround for results retrieval system
File ~\Anaconda3\lib\site-packages\pharmpy\modeling\common.py:238 in convert_model
new = nonmem.convert_model(model)
File …
```

Fix rate column issue (fixes #989)

---

src/pharmpy/modeling/block_rvs.py
src/pharmpy/plugins/nonmem/update.py

Running `tox -e py39 -- pytest --profile-svg -n8 tests`
Before:
After:
`covariance_matrix` is nowhere to be found.

[perf] Less calls to covariance matrix

---

.github/workflows/deploy.yml
.github/workflows/integration.yml
.github/workflows/main.yml
requirements.txt
tox.ini

[dev] Refactor tox configuration

---

src/pharmpy/workflows/dispatchers/local_dask.py

> Ready to MERGE @rikardn 
The default port (8787) causes user warnings because it clashes with one of the ports used by RStudio. Fixes #840.

[fix/ux] Use different port for dask distributed dashboard

---

src/pharmpy/tools/ruvsearch/tool.py
tests/integration/test_ruvsearch.py

Hi Rikard,
This PR is to check the input options of ruvsearch. For `modelfit_results`, I only check the residuals and predictions. I am not sure if I should check the ofv or not.?
Best regards,
Zhe

Check ruvsearch input (fixes #845)

---

src/pharmpy/tools/ruvsearch/results.py
src/pharmpy/tools/ruvsearch/tool.py

Hi Rikard,
This PR is to skip the proxy models which didn't have ofvs and only do the comparison between successful proxy models and the base model for each iteration. It would be great if we can have a test for this situation but I feel like it is really hard to have a failed proxy model as an example.
Best regards,
Zhe

Skip unsuccessful proxy models in ruvsearch (fixes #1097)

---

src/pharmpy/tools/__init__.py

The definition of `__dir__` was missing in the previous implementation. It broke tab completion and `pharmr` code generation.

[perf] Restore dynamic `pharmpy.tools` attributes

---

src/pharmpy/modeling/results.py

Hi Rikard,
@pharmpy-dev-123  and I found the significant digits would be printed after running the tool, e.g. iivsearch, so we thought it should be removed
Best regards,
Zhe

Do not print significant digits

---

pyproject.toml
src/pharmpy/plugins/nonmem/results_file.py
src/pharmpy/tools/__init__.py
src/pharmpy/tools/amd/run.py
src/pharmpy/tools/estmethod/__init__.py
src/pharmpy/tools/modelfit/__init__.py
tox.ini

The new environment can be used as `tox -e py38-type-check`.

[dev] Add type checking tox environment

---

docs/ruvsearch.rst

Hi Rikard,
This PR is to add documentation about the cwres_models in ruvsearch, so that users can distinguish between CWRES models and NLME models.
Best regards,
Zhe

Add documentation about cwres_models in ruvsearch

---

src/pharmpy/tools/ruvsearch/results.py

Hi Rikard, 
This PR is to solve the problem: ruvsearch terminated due to base CWRES model failure. I implemented the easiest way (I thought ) to solve it. But I am not sure if it is suitable or not. I couldn't add a test for it because I didn't have models for this situation. 
Best regards,
Zhe

Return empty results when base proxy model fail in each iteration (fixes #1179)

---

src/pharmpy/model/random_variables.py
tests/test_random_variables.py

Function to get random variables that have the same variance matrix (relevant for IOVs). Currently includes the input RV in the resulting RVs object. It also looks through all dists, does it make sense to do so or should it only look at IOVs?

Add function get_rvs_with_same_dist

---

requirements.txt

Q: How do we ensure this is not reverted by dependabot?

[deps] Exclude pywin32 versions 301 and 304 because of incompatibilities with conda

---

src/pharmpy/modeling/error.py
src/pharmpy/tools/amd/funcs.py
tests/modeling/test_error.py

Hi Rikard, 
This PR is to fix #969 by setting zero_protection = True as default.
Best regards,
Zhe

Set zero_protection=True as default in set_proportional_error_model (fixes #969)

---

requirements.txt
src/pharmpy/math.py
src/pharmpy/model/results.py
src/pharmpy/modeling/data.py
src/pharmpy/tools/qa/results.py
src/pharmpy/tools/scm/results.py

Needed some changes due to FutureWarnings. Some could be fixed, others had to be filtered out because of upstream usage in altair.
Note that all changes are compatible with the current `setup.py` constraint on `pandas` (`>=1.4`).
Replaces #1177. Fixes #1223.

[deps] Upgrade pandas to 1.5.0

---

src/pharmpy/tools/wrap.py
tests/tools/test_wrap.py

Appends `kwargs` to wrapper signature, needed in order for pharmr to add the R equivalence of `kwargs`.

Add kwargs to tool wrappers

---

src/pharmpy/internals/df.py
src/pharmpy/workflows/model_database/local_directory.py

This implementation takes data, dtypes, columns, and index into account for hash computation.

[fix] Make dataset deduplication independent of Python's hash seed

---

src/pharmpy/tools/amd/run.py
tests/tools/test_amd.py

[feature] Clarify error message when `search_space` cannot be parsed in `run_amd`

---

src/pharmpy/tools/amd/run.py
tests/tools/test_amd.py

> @rikardn Ready to MERGE
Since we do not change the dataset during AMD, we can check this upfront.

[feature] Error early on invalid occasion in `run_amd`

---

src/pharmpy/modeling/covariate_effect.py
src/pharmpy/tools/amd/run.py
src/pharmpy/tools/covsearch/tool.py
src/pharmpy/tools/mfl/feature/covariate.py
tests/tools/test_amd.py

> @rikardn Ready to MERGE
These changes make `run_amd` error on covariates missing from the `model.datainfo` and warn when `covsearch` is planned for execution but no covariates could be derived from the `search_space`.

[feature] Error and warn early on invalid or missing covariates in `run_amd`

---

src/pharmpy/modeling/lrt.py
tests/modeling/test_lrt.py

Two problems are fixed:
The next step would be to integrate the NONMEM error filtering that was already implemented in tool summaries.

[fix] Correct model selection in COVsearch

---

src/pharmpy/plugins/nlmixr/model.py
src/pharmpy/plugins/nonmem/run.py

> @rikardn Ready to MERGE
This is a very small addition to allow a generic access to `stdout` and `stderr` via the plugin metadata. In the future, this would allow, for instance, to create a plugin that spawn multiple subprocesses and still make sense of the captured outputs in a generic way.

[feature] Add stdout and stderr keys to plugin-specific metadata

---

src/pharmpy/modeling/write_csv.py
src/pharmpy/plugins/nlmixr/model.py

New function in pharmpy.plugin.nlmixr.model called verification(). Takes a nonmem model and a tool database name as input. Convert nonmem to nlmixr and compute predicted values to be compared to that of the nonmem model. If all predictions are within the margin of error (default to 10^-3), return True, otherwise False. If argument return_comp is True, instead return pd.dataframe with comparison of predictions from both models. Also added function modify_dataset() which takes in a model and returns a model with "evid" added to the dataset (mandatory for runnning nlmixr).
Some changes have also been made to convert_model() in order to achieve the wanted predictions and comparison.

Verification of conversion from nonmem to nlmixr2

---

src/pharmpy/model/estimation.py
src/pharmpy/modeling/estimation_steps.py
tests/model/test_estimation.py

Ensure strings for method, solver, and cov are correctly enclosed within single quotation marks

Fix string representation in EstimationStep.__repr__()

---

src/pharmpy/modeling/error.py
tests/modeling/test_error.py

Solution to the power model from issue #1589 (adding power model for multiple DVs)
This function can take in either a nothing at all or a specific DV and/or a list of epsilons to perform the transformation on. 
If nothing is specified, the function will perform the transformation on all epsilons that are available, regardless of the affected DV. I was unsure if this should be the case or if only the first (or only) DV should be affected instead, but I decided to follow the same principle as applied to set_iiv_on_ruv().
If a DV is specified, the model will only transform the epsilons connected to said DV (or the ones specified in the list of epsilons). 
If only a list of epsilons is provided, these will all be transformed, regardless of the connected DV.
Please let me know if there are any …

Support power residual error models for multiple dvs 

---

src/pharmpy/modeling/expressions.py
src/pharmpy/modeling/parameter_variability.py
tests/modeling/test_parameter_variability.py

Feature requested in issue #1708. There where some uncertainties regarding the issue description where "mu" was believed to be an ETA. An example of the implemented IIV addition, named "re_logit" in the add_iiv function, can be seen below.
S₁ = V
Is transformed to
phi_V = log( V / (1 - V))
S₁ = exp(ETA_S₁ + phi_V) / (1 + exp(ETA_S₁ + phi_V)
If there are any comments on the naming or implementation, please let me know!

Add rescale logit to add_iiv

---

src/pharmpy/tools/iivsearch/tool.py

Fixed small bug in iivsearch. Fixed parameters are now ignored so that workflow stops after `brute_force_no_of_etas` if number of unfixed etas <= 1.

Ignore fixed parameters in line 169 in tool.py

---

src/pharmpy/modeling/error.py

Allow the user to add power model to a symbol of their choosing.

Removed ValueError if trying to add power to non-matching IPRED symbol

---

src/pharmpy/tools/structsearch/pkpd.py
src/pharmpy/tools/structsearch/tool.py
tests/integration/test_structsearch.py
tests/tools/test_structsearch.py

I erroneously fixed `E_0` in the structsearch tool in a previous PR. Instead the initial estimates for `E_0`should be set based on a fit to the baseline PD model.

Unfix E_0 in structsearch

---

src/pharmpy/modeling/odes.py

Change `time_min`in `_get_absorption_init`in order to handle negative times in dataset.
This is referring to #1965

Ignore negative times in initial estimate

---

src/pharmpy/model/external/nonmem/model.py
src/pharmpy/model/external/nonmem/parsing.py
tests/nonmem/test_nonmem_model.py

Handle multiple DVs in nonmem models. 
`convert_model` and `parse_model` should handle multiple DVs correctly now.

Handle multiple DVs in nonmem models

---

src/pharmpy/modeling/expressions.py
tests/modeling/test_expressions.py

Fix bug in `get_pk_parameters` for models with an effect compartment.
Previously the input to the effect compartment has been changed and now the volume `V` is included into the input into the effect compartment. This resulted in the volume being removed from the pk parameters. Now only `KE0` is removed from the pk parameters.

Fix bug in get_pk_parameters

---

src/pharmpy/tools/external/nlmixr/run.py

Bug fix for running nlmixr using fit(model, tool="nlmixr")

Correct nlmixr execute_model() to follow same format as respective NONMEM function

---

src/pharmpy/model/external/nonmem/advan.py
src/pharmpy/model/external/nonmem/records/code_record.py
src/pharmpy/model/external/nonmem/update.py
src/pharmpy/model/statements.py
src/pharmpy/modeling/basic_models.py
src/pharmpy/modeling/common.py
src/pharmpy/modeling/covariate_effect.py
src/pharmpy/modeling/data.py
src/pharmpy/modeling/expressions.py
src/pharmpy/modeling/odes.py
src/pharmpy/modeling/results.py
src/pharmpy/tools/amd/funcs.py
tests/model/test_statements.py
tests/modeling/test_odes.py
tests/nonmem/test_advan.py
tests/tools/test_start_model.py

Added update to both support multiple doses per compartment as  well as the parsing ability of these models. Models with multiple doses require either a CMT column or an admid column in order to work correctly. Changes some naming convention to be more streamline with the number of doses. For instance
ode_system.dosing_compartment -> dosing_compartments
Compartment.dose -> Compartment.first_dose (if only interested in dose, as .dose will return a tuple)
Let me know if there are any comments

Multiple doses per compartment and parsing updates for IV+ORAL

---

src/pharmpy/tools/structsearch/pkpd.py
src/pharmpy/tools/structsearch/tool.py
tests/tools/test_structsearch.py

Add initial estimates for emax and ec50 as user input in structsearch. 
If none are specified the initial estimates will be determined from model.modelfit_results.parameter_estimates.

Add initial ests for emax and ec50 as user input

---

src/pharmpy/tools/amd/run.py
src/pharmpy/tools/mfl/feature/covariate.py
src/pharmpy/tools/mfl/grammar.py
src/pharmpy/tools/ruvsearch/tool.py
src/pharmpy/tools/structsearch/pkpd.py
tests/tools/test_mfl.py

Modify AMD for PKPD models.
It is now possible to run the AMD tool for PKPD models (only the PD part).
- Added initial estimates for E_max and EC_50 as user input
- Added @PD, @PK, @PD_IIV and @PK_IIV to the covariates search space

Modify AMD for PKPD models

---

src/pharmpy/modeling/__init__.py
src/pharmpy/modeling/expressions.py
src/pharmpy/modeling/pd.py
src/pharmpy/tools/amd/run.py
src/pharmpy/tools/structsearch/pkpd.py
src/pharmpy/tools/structsearch/tool.py
tests/modeling/test_expressions.py
tests/modeling/test_pd.py
tests/tools/test_mfl.py
tests/tools/test_structsearch.py

Changes made in this PR:
- add indirect effect/turnover models
- Parameter name change: E_0 → B (baseline)
- Remove step effect from pkpd model scope
- lower bound for Emax = -1
- Emax = theta * eta (proportional iiv)
- Initial estimate for slope = Emax/EC50
- Emax, EC50, baseline and MET inits = user input

Add indirect effect models

---

src/pharmpy/modeling/__init__.py
src/pharmpy/modeling/expressions.py
src/pharmpy/modeling/parameter_variability.py
src/pharmpy/tools/amd/run.py
src/pharmpy/tools/iivsearch/tool.py
src/pharmpy/tools/structsearch/pkpd.py
src/pharmpy/tools/structsearch/tool.py
tests/modeling/test_expressions.py

Changes made in this PR:
- iivsearch: 
- add iiv_strategies `pd_add_diagonal` and `pd_fullblock`. They perform the same operations as `add_diagonal` and `fullblock` but only add iivs to pd parameters
- Add function `add_pd_iiv` to parameter_variability.py. This functions adds iiv to all pd parameters that do not already have iiv
- amd tool
- iivstrategy is `pd_fullblock` if `modeltype == pkpd`
- simplified `get_pd_parameters` because the function could not handle more complex functions such as indirect effect models. Now the parameters are hard coded. This needs to be updated later.
- Allow integer initial estimates for pkpd models. Previously they had to be floats.

Adapt iivsearch fullblock for pd models

---

src/pharmpy/modeling/parameter_variability.py
tests/modeling/test_parameter_variability.py

Fixed bug in `remove_iiv` so that ETA is properly removed even for proportional and logit iivs.

Fix bug in remove_iiv

---

src/pharmpy/modeling/odes.py
src/pharmpy/tools/amd/run.py
src/pharmpy/tools/structsearch/drugmetabolite.py
src/pharmpy/tools/structsearch/tool.py
tests/tools/test_structsearch.py

Possibility of specifying "drug_metabolite" modeltype within the AMD tool which will run structsearch for drug_metabolite.
Also updated structsearch for drug_metabolite to always return a drug metabolite model by using a "plain" type model as base.
In addition to these implementations. Functionality for extracting CL, V and Q parameters connected to a metabolite has been introduced for accurate extraction of all parameters of interest when running drug metabolite models.

Implement drug metabolite within AMD

---

src/pharmpy/model/estimation.py
src/pharmpy/model/external/nonmem/update.py
tests/modeling/test_estimation_steps.py
tests/nonmem/test_nonmem_model.py

This commit enriches the $COVARIANCE command with more detailed default options (UNCONDITIONAL, PRINT=E, PRECOND=1), enhancing the output and success rate of the covariance step.
* Modified docstring in estimation.py to explain the new default options.
* Updated update.py to incorporate the new default options in the $COVARIANCE command.
* Adjusted test cases in test_estimation_steps.py and test_nonmem_model.py to reflect and test the new defaults.
These improvements aim to facilitate more insightful and stable model development.

Update $COVARIANCE command with new default options

---

src/pharmpy/modeling/common.py
src/pharmpy/modeling/odes.py
src/pharmpy/tools/amd/run.py
src/pharmpy/tools/common.py
src/pharmpy/tools/mfl/feature/absorption.py
src/pharmpy/tools/mfl/feature/elimination.py
src/pharmpy/tools/mfl/feature/lagtime.py
src/pharmpy/tools/mfl/feature/transits.py
src/pharmpy/tools/mfl/grammar.py
src/pharmpy/tools/mfl/parse.py
src/pharmpy/tools/mfl/statement/feature/absorption.py
src/pharmpy/tools/mfl/statement/feature/elimination.py
src/pharmpy/tools/mfl/statement/feature/lagtime.py
src/pharmpy/tools/mfl/statement/feature/peripherals.py
src/pharmpy/tools/mfl/statement/feature/transits.py
src/pharmpy/tools/modelsearch/algorithms.py
src/pharmpy/tools/modelsearch/tool.py
tests/modeling/test_odes.py
tests/tools/test_mfl.py
tests/tools/test_modelsearch.py

Implementation of a new ModelFeatures class allowing for easier handling of MFL attributes within the different tools. Currently implemented for allowing modelsearch to be rerun (or run with any model as a start model).
The MFL string in modelsearch is now representing the entire search space for modelsearch and if the input model is not part of said search space. A base model will be created which is part of it. If the input model is part of the search space, the base model will be the same as the input model.

ModelFeatures class and rework of modelsearch for rerunning

---

src/pharmpy/tools/amd/run.py

If model is missing results when running "drug_metabolite" in AMD, the dataset need to be filtered for DVID=1 before fitting. This filtering is reset during structsearch (after modelsearch has been run)

Auto filter dataset before fitting if missing results for drug_metabolite

---

src/pharmpy/tools/structsearch/pkpd.py
src/pharmpy/tools/structsearch/tool.py
tests/tools/test_structsearch.py

Changes to structsearch for PKPD models:
- initial estimate for baseline is used for all PKPD models
- initial estimates for IIVs is set to 0.1
- mat -> met

Make changes to structsearch for pkpd

---

docs/amd.rst
docs/modelsearch.rst
docs/tools.rst

Update the MFL documentation and added instantaneous absorption type as well as ON/OFF arguments for lagtime.
For the modelsearch documentation, I added information regarding the new workflow logic regarding the addition of a base model and explicit search spaces.
I would love some feedback regarding the modelsearch workflow to make sure it is clear and understandable :)

Updated MFL- and modelsearch docs

---

src/pharmpy/model/estimation.py
src/pharmpy/model/external/nonmem/nmtran_parser.py
src/pharmpy/model/external/nonmem/update.py
tests/modeling/test_estimation_steps.py
tests/nonmem/test_parser.py

This PR adds EFIM (Expected Fisher Information Matrix) support.
Add 'EFIM' to `supported_parameter_uncertainty_methods` in `estimation.py`.
Introduce a new function `add_efim_records` that manipulates the control stream for EFIM calculations.
Resolves Issue #2004

Add `$DESIGN` (EFIM) support

---

src/pharmpy/tools/amd/run.py

When implementing filter_dataset() for drug metabolite models, it was accidentally  filtered for only DVID=1 instead of all DVID different from 2. This causes an incorrect filtration of drug metabolite models and an error when running AMD.

Correct drug metabolite filtration

---

src/pharmpy/tools/structsearch/tool.py

Structsearch for TMDD was disabled before the last release. Enabled again now for testing.

Enable TMDD for structsearch

---

src/pharmpy/tools/estmethod/algorithms.py
tests/integration/test_estmethod.py
tests/tools/test_estmethod.py

With the modifications in this PR, `IMP EONLY=1` will only be added when multiple estimation methods are to be compared or when the `exhaustive_only_eval` is used.
Previously, the IMP evaluation was automatically added to every model during the run of the `estmethod` tool when only evaluating different `$COV`, and it couldn't be disabled.
Resolves: First point in issue #1899

Don't always add `IMP EONLY=1` when running `estmethod`

---

src/pharmpy/model/external/nonmem/update.py
src/pharmpy/modeling/__init__.py
src/pharmpy/modeling/data.py
tests/nonmem/test_advan.py
tests/nonmem/test_nonmem_model.py

Update CMT column in response to issue #2060. Will now only update if needed. In other cases (as with a previously dropped CMT column) a new CMT column will be generated, overwriting the previous one.

Update to automatic CMT column update

---

src/pharmpy/tools/structsearch/drugmetabolite.py
src/pharmpy/tools/structsearch/tool.py

Fix an error where the OFV value of candidate models used the OFV from the input model in drug metabolite structsearch. Also corrected so the right parent model per model is set

Calculate the correct BIC for drug metabolite

---

src/pharmpy/tools/mfl/parse.py

Fix issue where the least number of transformation encountered an error will trying to determine the LNT for search spaces where both search spaces only had one depot option for the transit argument, and it was the same for both search spaces.

Fix least number of transformations for transits

---

src/pharmpy/tools/modelsearch/tool.py

Fix an issue will summarizing the results in modelsearch where models with results "None" tried to be indexed in the table "summary_models"

Only index models with results not None in summary_models

---

docs/structsearch.rst
src/pharmpy/tools/amd/run.py
src/pharmpy/tools/structsearch/drugmetabolite.py
src/pharmpy/tools/structsearch/tool.py
tests/tools/test_structsearch.py

Drug metabolite models will now run with the default modelsearch search space for the parent drug metabolite
Candidate models is also dependent on the administration route and presystemic drug metabolite models are only created for oral/ivoral administration

Drug metabolite default search space and correct candidate models

---

src/pharmpy/tools/__init__.py
src/pharmpy/tools/amd/run.py
src/pharmpy/tools/common.py
src/pharmpy/tools/covsearch/tool.py
src/pharmpy/tools/iivsearch/tool.py
src/pharmpy/tools/iovsearch/tool.py
src/pharmpy/tools/run.py
src/pharmpy/tools/ruvsearch/tool.py
tests/integration/test_amd.py
tests/tools/test_run.py

Add strictness to
- IIVSearch
- IOVSearch
- COVSearch
- RUVSearch
- AMD
Add a warning when all models fail the strictness criteria.
COVSearch: Add column 'strictness_fulfilled' to summarize_tool table that states whether the model is passing or failing the strictness criteria.

Implement strictness to other tools

---

src/pharmpy/modeling/odes.py
src/pharmpy/modeling/tmdd.py
tests/modeling/test_tmdd.py

There was an issue when creating QSS models from a model with mixed MM FO elimination. 
One problem was that in `set_first_order_elimination` the volume parameter was either 'V' or 'VC' but could not be e.g. 'V1'. This created problems in some cases.
Another problem was that for some models too many statements for the volume parameter were added. E.g. 
`VC = ...`
`V = VC`
`V1 = V`
That caused problems.

Fix parameter issue for models with mixed-fo-mm elimination

---

src/pharmpy/tools/structsearch/tmdd.py

Add initial estimate to IIV_R0 if IIV_CLMM does not exist in the parent model.

Add initial estimate to IIV_R0

---

src/pharmpy/modeling/allometry.py
src/pharmpy/modeling/covariate_effect.py
src/pharmpy/tools/amd/run.py

Automatically adds the allometry scaled covariate effect to the covsearch searchspace (which prevents them from being removed)
Also changed to not add allometric scaling if covariate effect already exist for the parameter, using the allometric variable as covariate

Avoid removing allometry scaling in AMD

---

src/pharmpy/tools/external/nonmem/run.py

Previoulsy connected modelfit_results objects will now be removed when using ModelEntry (if connected)

Fix crashing modelsearch due to wrongfully connected modelfit_results object

---

test-requirements.txt

Revert "Bump pytest-xdist from 2.5.0 to 3.3.1"

---

.github/actions/setup-tox/action.yml
pretest-requirements.txt

We currently have no control over which version of tox gets installed in the continuous integration tests.

New requirements.txt for pip and tox (and deps)

---

src/pharmpy/modeling/allometry.py

When adding allometric scaling. If no allometric variable is defined, try to extract one from the dataset based on "body weight" descriptor instead of using "WT" as the default value

Default allometric variable based on "body weight" instead of using "WT"

---

src/pharmpy/model/external/rxode/model.py
src/pharmpy/tools/external/nlmixr/run.py
src/pharmpy/tools/external/rxode/run.py
src/pharmpy/tools/modelfit/tool.py

Fix backslash issue in file path for windows when running RxODE and nlmixr. Also added support for running fit(model, "rxode") and similar updates to RxODE as for nlmixr in #2303

Correct windows path for fix_eta file and updates to RxODE

---

src/pharmpy/tools/amd/run.py

Changes made:
- Add default order for pkpd models in AMD (without allometry and iovsearch)
- Fix bug with search space for pkpd models. Before there was no default search space when the search space was not None. So if the search space contained covariates then it was not None and therefore no default search space was used. This is fixed now.

Add default order for AMD for pkpd + fix bug

---

src/pharmpy/tools/covsearch/tool.py

Add model to `is_strictness_fulfilled` in covsearch after `is_strictness_fulfilled` has been updated.
Currently model is missing from that function and covsearch fails.

Add model to is_strictness_fulfilled in covsearch

---

docs/structsearch.rst
docs/tools.rst
src/pharmpy/modeling/odes.py
src/pharmpy/tools/amd/run.py
src/pharmpy/tools/covsearch/tool.py
src/pharmpy/tools/mfl/feature/metabolite.py
src/pharmpy/tools/mfl/feature/peripherals.py
src/pharmpy/tools/mfl/filter.py
src/pharmpy/tools/mfl/grammar.py
src/pharmpy/tools/mfl/helpers.py
src/pharmpy/tools/mfl/interpreter.py
src/pharmpy/tools/mfl/statement/feature/metabolite.py
src/pharmpy/tools/mfl/statement/feature/peripherals.py
src/pharmpy/tools/modelsearch/algorithms.py
src/pharmpy/tools/modelsearch/tool.py
src/pharmpy/tools/structsearch/drugmetabolite.py
src/pharmpy/tools/structsearch/tool.py
tests/tools/test_mfl.py
tests/tools/test_structsearch.py

Added "METABOLITE" option within MFL with two options
- PSC (pre-systemic circulation)
- BASIC (simple 100 conversion from of parent to metabolite)
Also updated "PERIPHERALS" to handle a second (optional) argument with two possible entries, either "DRUG" which would add peripherals to the central compartment, or "MET" which would instead add the peripherals to the present METABOLITE compartment. This is based on DVID for the moment, with DVID=2 representing the metabolite

Add MFL for drug metabolite

---

src/pharmpy/modeling/allometry.py
src/pharmpy/modeling/covariate_effect.py
src/pharmpy/tools/amd/run.py

Added allometric scaling effects are now extracted and added to the covsearch search space in order to be left in the model when allometry is performed before covsearch
Also implemented better determination technique for covariate effects in order to more accurately be able to determine the effect type in more complex expressions.

Avoid removing allometry scaling in covsearch

---

docs/amd.rst
docs/covsearch.rst
docs/tools.rst
src/pharmpy/modeling/covariate_effect.py
src/pharmpy/modeling/lrt.py
src/pharmpy/tools/amd/run.py
src/pharmpy/tools/covsearch/tool.py
src/pharmpy/tools/mfl/feature/covariate.py
src/pharmpy/tools/mfl/grammar.py
src/pharmpy/tools/mfl/parse.py
src/pharmpy/tools/mfl/statement/feature/covariate.py
src/pharmpy/tools/mfl/statement/feature/symbols.py
src/pharmpy/tools/mfl/stringify.py
tests/integration/test_amd.py
tests/tools/test_covsearch.py
tests/tools/test_mfl.py

Updates to covsearch for handling of optional and mandatory covariates using the COVARIATE(...) vs COVARIATE?(...) notation
Also added possibility of defining mechanistic covariates as argument for AMD which would cause AMD to run a initial covsearch run with the specified covariates.
ModelEntry has also now been implemented for covsearch as a part of this update

Rework covsearch for structural/mechanistic and exploratory covariates

---

src/pharmpy/tools/common.py

Raise error when all models fail strictness.
Should this be a warning instead of an error?

Raise error when all models fail strictness

---

src/pharmpy/tools/mfl/parse.py

Correctly expand optional/non-optional covariates in MFL class

Correctly expand covariate mfl statements

---

src/pharmpy/tools/amd/run.py

- Dataset filtering now before modelfit (before it was done after)
- Filtering is only performed when `dv_types` is not None.

Fix bugs with dataset filtering for TMDD in AMD

---

docs/amd.rst
docs/retries.rst
src/pharmpy/modeling/parameter_sampling.py
src/pharmpy/modeling/results.py
src/pharmpy/tools/amd/run.py
src/pharmpy/tools/frem/results.py
src/pharmpy/tools/retries/tool.py
tests/integration/test_retries.py
tests/modeling/test_parameter_sampling.py
tests/modeling/test_results.py
tests/tools/test_frem.py

- parameter_sampling can now sample on both normal and UCP scale.
- Retries tool using create_rng instead of random.random
- Added argument "rng" to AMD tool for random sampling (currently only for retries tool)

Integrate parameter_sampling in retries tool

---

src/pharmpy/tools/amd/run.py

Remove `res.models` because `models` will be removed from the results object in the future.
Use `res.tool_database.model_database.retrieve_model` instead.

Remove res.models from structsearch for TMDD

---

src/pharmpy/modeling/tmdd.py
src/pharmpy/tools/structsearch/tool.py
tests/modeling/test_tmdd.py

- Add total drug and total target to TMDD models
- If total drug is dv = 1 then the original dv is overwritten
- Fix bug that required the model to have an IPRED for QSS and Wagner models.

Add total drug and total target to TMDD

---

src/pharmpy/modeling/odes.py
tests/modeling/test_odes.py

- function `find_volume_parameters` does now work for mixed elimination models
- `add_peripheral_compartment`worked only for some models with mixed elimination (see #2463 ). Should now work for all models. 
- small fix in `get_central_volume_and_clearance`.

Fix volume issues for mixed elimination models

---

src/pharmpy/tools/allometry/tool.py
src/pharmpy/tools/common.py
src/pharmpy/tools/covsearch/tool.py
src/pharmpy/tools/funcs/summarize_individuals.py
src/pharmpy/tools/run.py
src/pharmpy/tools/ruvsearch/tool.py
tests/integration/test_iivsearch.py
tests/integration/test_modelsearch.py
tests/tools/test_run.py
tests/tools/test_summarize_individuals.py

Remove workarounds in `tools/common.py` that attaches `ModelfitResults` to `Model`, various fixes where `ModelEntry` was not used.

Add model entry in tool summaries

---

src/pharmpy/tools/amd/run.py

Change ruvsearch for TMDD in AMD so that ruvsearch is run for all dvs in `dv_types`.

Fix ruvsearch for multiple DVs in AMD for TMDD

---

src/pharmpy/tools/structsearch/tool.py

Remove unused function `_results`

Remove unused function in structsearch

---

docs/amd.rst
src/pharmpy/tools/amd/run.py
src/pharmpy/tools/mfl/parse.py
src/pharmpy/tools/modelsearch/tool.py
tests/integration/test_amd.py
tests/tools/test_amd.py

Remove the order option from AMD and instead implement new argument "strategy" for defining how to run the tools. Currently there are two strategies implemented:
- SIRIAC (Structural IIVsearch, RUVsearch, IOVsearch, Allometry, Covariate)
- SIRIACIR (Structural IIVsearch, RUVsearch, IOVsearch, Allometry, Covariate IIVsearch, RUVsearch)
Any other ideas for naming of said strategies are much appreciated.
As order was removed, some reformatting of the validation of the input arguments of AMD has also been done (in order to ease testing of the arguments among other things)

Pre-defined strategies for order in AMD

---

src/pharmpy/internals/fn/type.py
src/pharmpy/modeling/blq.py
src/pharmpy/modeling/parameter_variability.py
src/pharmpy/modeling/pd.py
src/pharmpy/modeling/tmdd.py
src/pharmpy/tools/amd/run.py
src/pharmpy/tools/covsearch/tool.py
src/pharmpy/tools/estmethod/tool.py
src/pharmpy/tools/iivsearch/tool.py
src/pharmpy/tools/iovsearch/tool.py
src/pharmpy/tools/modelsearch/tool.py
src/pharmpy/tools/retries/tool.py
src/pharmpy/tools/ruvsearch/tool.py
src/pharmpy/tools/structsearch/tool.py
tests/tools/test_covsearch.py
tests/tools/test_estmethod.py
tests/tools/test_iivsearch.py
tests/tools/test_iovsearch.py
tests/tools/test_modelsearch.py
tests/tools/test_ruvsearch.py
tests/tools/test_structsearch.py

- Implementation of `Literal` in type hints for all subtools, transform_blq, pkpd and tmdd.
- Additional error message for type `Literal` so that the error message looks nicer (as in `check_list`). Is that needed? This does not work if type is `Optional[Literal]`.
- Now arguments of type `Literal` are checked in internals/fn/type.py and do not need extra validation functions.
Possible issues:
- With Literals the arguments are case sensitive. Is that a problem?
- In structsearch the types are checked before the functions in `validate_input`. E.g. `dv_types` is checked before validating that `dv_types` is even a valid argument (e.g. for type `pkpd`). But if type is `pkpd` then validation of `dv_types` is unnecessary.

Use literals in typehints

---

src/pharmpy/tools/iivsearch/tool.py

Fix #2422
Fixes problem in IIVsearch when using the "no_add" iiv_strategy method. The bug where only for the "no_add" iiv_strategy when the base model (input model) was the final model in the tool.

Avoid trying to extract input model from IIVsearch database

---

src/pharmpy/tools/amd/run.py

Add parameter_uncertainty_method argument in AMD tool.
I chose the name `parameter_uncertainty_method` since that name is used in other parts of Pharmpy. It might be more confusing to introduce a new name. But I am open to suggestions.
$DESIGN is currently not supported.

Add parameter_uncertainty_method to AMD options

---

src/pharmpy/tools/amd/run.py

- Add type check for `parameter_uncertainty_method`.
-  Use `@with_runtime_arguments_type_check` on `run_amd` instead of on `validate_input`
- Remove type hints from `validate_input`

Fix type hint for parameter_uncertainty_method

---

docs/amd.rst
src/pharmpy/modeling/__init__.py
src/pharmpy/modeling/covariate_effect.py
src/pharmpy/tools/amd/run.py
src/pharmpy/tools/covsearch/tool.py
src/pharmpy/tools/mfl/parse.py
src/pharmpy/tools/mfl/statement/feature/covariate.py
tests/tools/test_amd.py
tests/tools/test_covsearch.py
tests/tools/test_mfl.py

Fixes crashing AMD integration test
Simplifies covariate effect extraction
Allows for param/covariate combinations (as tuples) for structural covariate effects in AMD

Simplify covariate extraction and allow param/covariate combination in AMD

---

src/pharmpy/tools/structsearch/tmdd.py
src/pharmpy/tools/structsearch/tool.py
tests/tools/test_structsearch.py

Remove TMDD models with fewer than 2 dvs from structsearch because there is no DV filtering for single dvs

Remove TMDD models that have less than two dvs

---

docs/amd_tmdd.rst
docs/tmdd.rst
src/pharmpy/modeling/tmdd.py

Make it clear that all observations are treated as drug if `dv_types`is set to `None`.

Add info to dv_types for TMDD

---

src/pharmpy/tools/amd/run.py
src/pharmpy/tools/structsearch/pkpd.py
tests/integration/test_structsearch.py

- Remove structural covariates from AMD for PKPD models
- Fix bug in structsearch for PKPD
- Activate integration tests for mac and linux

Remove structural covariates from amd for pkpd models

---

docs/amd_pkpd.rst

Update AMD PKPD documentation.
#2822 needs to be merged in before this PR.

Update AMD PKPD documentation with removed structural covariates

---

docs/iivsearch.rst
src/pharmpy/tools/iivsearch/tool.py
tests/integration/test_iivsearch.py
tests/tools/test_iivsearch.py

Should fix #2776.
Warns the user if parameters are given in the "keep" argument that are not found in the model (this includes the default value of "CL")

Default keep=["CL"] in IIVSearch

---

src/pharmpy/tools/amd/run.py

Peripherals must now be tuples.

Change peripherals to tuple

---

src/pharmpy/tools/amd/run.py

Move `all_models`outside of the if statement so that it can be used further down as well.

Move all_models outside of if statement

---

src/pharmpy/modeling/expressions.py
tests/modeling/test_expressions.py

A model being created with first order absorption as well as a number of transit compartments will have somewhat redundant k-rate parameters. The following example would create such a model
```
model = load_example_model("pheno")
model = set_first_order_absorption(model)
model = set_transit_compartments(model, 3)
```
The assignments in question would be the following
```
MAT = POP_MAT
KA = 1/MAT
K45 = KA
```
And through this, MAT was previously not caught as an individual parameter.

Correct extraction of redundant K-rate individual parameters

---

src/pharmpy/model/statements.py
tests/modeling/test_pd.py

When using `central_compartment` for an indirect effect model the response compartment was returned instead of the central compartment.

Fix problem with central compartment being Response compartment

---

src/pharmpy/modeling/estimation.py
tests/modeling/test_estimation.py

Substitute fixed parameter symbols when calculating new UCP parameters

---

src/pharmpy/tools/allometry/report.rst
src/pharmpy/tools/allometry/tool.py
src/pharmpy/tools/amd/run.py
src/pharmpy/tools/common.py
src/pharmpy/tools/covsearch/report.rst
src/pharmpy/tools/iivsearch/report.rst
src/pharmpy/tools/iivsearch/tool.py
src/pharmpy/tools/iovsearch/report.rst
src/pharmpy/tools/modelsearch/report.rst
src/pharmpy/tools/retries/report.rst
src/pharmpy/tools/ruvsearch/report.rst
src/pharmpy/tools/ruvsearch/tool.py
src/pharmpy/tools/structsearch/report.rst

- add `modelfit_results` to `results` object so that `modelfit_results` can be piped instead of parsed.
- remove `final_model_parameter_estimates` from `results`
- Fix model database/context issues in AMD

Add modelfit_results to results object

---

src/pharmpy/model/execution_steps.py
src/pharmpy/model/external/nonmem/parsing.py
src/pharmpy/workflows/results.py
tests/model/test_estimation.py
tests/nonmem/test_nonmem_model.py
tests/workflows/test_hashing.py

Single .derivative attribute instead of splitting ETA/EPS in EstimationStep. Derivatives are always with respect to the prediction.
Derivatives are stored as a tuple of tuples where each tuple represent one derivative. Each element within the tuples are required to be a symbol of type pharmpy.basic.Expr.

Restructure derivative handling

---

docs/covsearch.rst
src/pharmpy/tools/covsearch/tool.py
tests/integration/test_covsearch.py
tests/tools/test_covsearch.py

Possibility of setting the adaptive scope reduction (from scm+) and max eval when running covsearch.
Should implement #2881 as well as #2880

Adaptive scope reduction and max eval option for covsearch

---

src/pharmpy/tools/covsearch/tool.py
src/pharmpy/tools/mfl/grammar.py
src/pharmpy/tools/mfl/statement/feature/covariate.py
tests/tools/test_covsearch.py
tests/tools/test_mfl.py

Raise error when parsing unknown covariate effects. As a placeholder for unsupported types, "CUSTOM" can be used to store an effect.

Disallow unsupported covariate effect types in MFL parsing

---

src/pharmpy/tools/external/nlmixr/run.py
src/pharmpy/tools/run.py

- Warn the user when running tool with input model of a different type than that of the defined "esttool"
- Avoid storing model code of the input model type alongside nlmixr code when running a tool with nlmixr if the input model is of a different type

Update nlmixr fitting

---

src/pharmpy/tools/allometry/tool.py
src/pharmpy/tools/common.py
src/pharmpy/tools/covsearch/tool.py
src/pharmpy/tools/iivsearch/tool.py
src/pharmpy/tools/iovsearch/tool.py
src/pharmpy/tools/linearize/tool.py
src/pharmpy/tools/modelsearch/tool.py
src/pharmpy/tools/retries/tool.py
src/pharmpy/tools/ruvsearch/tool.py
src/pharmpy/tools/structsearch/tool.py

When storing the input and final model within `create_results`, sometimes the wrong model was stored (as some of the tools manipulate the final model, for instance covsearch). Now, each tool stores the input model and final model themselves.

Store input/final model within each tool

---

src/pharmpy/tools/mfl/parse.py

PD effects were not considered when comparing two MFLs. Now they are included.

Add PD MFLs to eq

---

src/pharmpy/tools/iivsearch/tool.py
tests/tools/test_iivsearch.py

Raise in IIVSearch if parameter in keep-option does not exist, warn if no IIV exists.

More detailed checks of `keep`-option in IIVSearch 

---

src/pharmpy/tools/external/nlmixr/run.py

This pull request addresses an issue where the script was failing to locate the Rscript executable on Windows. On Windows, the executable is named Rscript.exe, but the script was checking for Rscript, which caused path.is_file() to return False.

fix: Add Windows support for Rscript executable in get_rpath function
