- src/pharmpy/tools/resmod/results.py
- src/pharmpy/tools/resmod/tool.py
Hi, here are two commits for final estimates in resmod. The first one is to add the final estimates into the resmod models data frame as parameters, the second one is to use the parameters as the initial estimates for setting up full models.
> Final estimates in resmod

- src/pharmpy/modeling/__init__.py
- src/pharmpy/modeling/data.py
- tests/modeling/test_data_funcs.py
Hi Rikard,
I add the series of zero mdv when there is no dose in the dataset. I use the length of DV to create the series, I am not sure it is the best way or not...
> Add zero values for mdv when only observations

- src/pharmpy/statements.py
- tests/test_statements.py
> Add insert_after method to ModelStatements

- src/pharmpy/tools/resmod/tool.py
Hi Rikard,
This commit is to fix the issue that we have different OFV values in Resmod of Pharmpy and PsN.
> Add id column in resmod dataset

- src/pharmpy/tools/resmod/results.py
- src/pharmpy/tools/resmod/tool.py
Hi Rikard,
Here is the combined error model. This commit included combined error model in resmod and the original model transformation when combined error model is the best resmod model. I will force IPRED equal to a small value when it is zero in the next commit:)
> Add combined error model in resmod

- src/pharmpy/modeling/__init__.py
- src/pharmpy/modeling/error.py
- tests/modeling/test_error.py
Hi Rikard, 
Here is the add_time_varying_error function. After this task, I am going to change the models and workflow in resmod:)
> Add time varying error model function

- src/pharmpy/tools/resmod/results.py
- src/pharmpy/tools/resmod/tool.py
Hi Rikard,
Here is time varying error in Resmod. I tried my best to make the code general but I still have some questions on this code. For example, now we give a default: groups = 4, so I know it will generate 3 models, so I add three models in `calculate_results` function of results.py and `_create_best_model` of tool.py directly. I guess maybe it is possible to let the models change according to the groups number we give automatically by loop but I haven't found a way to do that. Maybe you can have a look at my code and give me some comments first? So far it should work for adding 3 time varying error models in Resmod. 
Thank you very much!
Best regards,
Zhe Huang
> Time varying error resmod

- src/pharmpy/tools/resmod/results.py
- src/pharmpy/tools/resmod/tool.py
Hi Rikard,
I am so sorry that I found two issues in my codes of resmod, I have fixed them in this PR. I can tell Tianwu how to change the code before you release a new version.
Best regards,
Zhe Huang
> Fix two issues in resmod

- src/pharmpy/modeling/power_on_ruv.py
- src/pharmpy/tools/resmod/tool.py
- tests/modeling/test_modeling.py
Hi Rikard,
Here is the zero protection for power model and special combined model in resmod. I think for combined error, maybe the easier way is to avoid zero IPRED in dataset. I also tried to change the expression of combined model but it seems more complicated and I haven't figured it out. If it is the better way, I can continue working on it :) 
Best regards,
Zhe Huang
> Zero protection

- src/pharmpy/tools/resmod/tool.py
- tests/integration/test_resmod.py
Hi Rikard,
This commit is to add p-value as an option with default 0.05. Because df is always equal to 1 in resmod so I didn't calculate it.
Best regards,
Zhe Huang
> Add p-value option in resmod

- src/pharmpy/modeling/error.py
- tests/modeling/test_error.py
Hi Rikard,
This commit is to change the combined error model expression for models that have three extended errors. The three extended error are: iiv_on_ruv, time_varying and iiv_on_ruv+time_varying.
I found a way to get specific expression and condition from a piecewise function in Stackoverflow and it works! The codes I write in line 331-333 look very weird but I had to substitute the previous proportional epsilon in the input model with the new proportional epsilon, otherwise, I will have three epsilons in the random variables(previous proportional epsilon, new proportional epsilon, new additive epsilon ), then the nonmem code cannot generate the correct expression and have `EPS(3)` in the code. I guess maybe there is a better way to do it? 
Thank you!
Best regards,
Zhe Huang
> Set combined error expression when input model has extended errors

- src/pharmpy/tools/resmod/tool.py
Hi Rikard,
There is an issue in resmod and the commit is about fixing this issue.
Have a nice day!
Best regards,
Zhe Huang
> Fix resmod issue

- src/pharmpy/modeling/amd.py
Hi Rikard, 
This commit is to fix issue #581 
Best regards,
Zhe Huang
> Add skip list to avoid unnecessary tasks in resmod

- src/pharmpy/modeling/__init__.py
- src/pharmpy/modeling/summarize_individuals.py
- src/pharmpy/tools/modelsearch/tool.py
- tests/integration/test_modelsearch.py
Implementation at https://github.com/pharmpy/pharmpy/blob/48674953f5bcdc649ccbd712c8617414cad6f39c/src/pharmpy/modeling/summarize_individuals.py#L10
Attribute definition at https://github.com/pharmpy/pharmpy/blob/48674953f5bcdc649ccbd712c8617414cad6f39c/src/pharmpy/tools/modelsearch/tool.py#L87
Includes one integration test at https://github.com/pharmpy/pharmpy/blob/48674953f5bcdc649ccbd712c8617414cad6f39c/tests/integration/test_modelsearch.py#L222
> Add summary_individuals attribute to ModelSearchResults

- docs/contribute.rst
> Add examples on how to use the integration and run venv

- src/pharmpy/tools/resmod/tool.py
Hej Rikard,
I just finished the abstract and am waiting for review, so I think I can go back to my development tasks when I am waiting:) This commit is to solve the issue of comparing the full model results in resmod.
Best regards,
Zhe Huang
> Change the best model name and predecessors of task_results in resmod (fixes pharmpy#635)

- src/pharmpy/config.py
- src/pharmpy/modeling/common.py
- src/pharmpy/modeling/run.py
- src/pharmpy/plugins/nonmem/__init__.py
- src/pharmpy/utils.py
- src/pharmpy/workflows/execute.py
> [feature] Expand tilde to user `$HOME` when handling user input paths

- src/pharmpy/datainfo.py
- src/pharmpy/model.py
- src/pharmpy/plugins/nonmem/model.py
- src/pharmpy/workflows/model_database/local_directory.py
- tests/modeling/test_common.py
- tests/test_model.py
This is a squashed version of #680 that was reverted in #690.
> [fix] Correct and generic implementation of `Model#__eq__` (squashed)

- src/pharmpy/results.py
As long as its `__class__` `__qualname__` ends with `"Results"`. Also, centralizes the codec definition.
> [refactor] Allow any results object class to be stored in `results.json`

- src/pharmpy/modeling/summarize_individuals.py
> [feature] Set ID column name and rename dofv column in summarize_individuals

- src/pharmpy/modeling/amd.py
- src/pharmpy/tools/amd/funcs.py
Hi Rikard,
This PR is the solution for today's issue. I feel like it may be better to commit now rather than after all issues are solved:)
Best regards,
Zhe Huang
> Generate correct dataset for start model in amd

- src/pharmpy/plugins/nonmem/__init__.py
- src/pharmpy/plugins/nonmem/run.py
Fixes https://github.com/pharmpy/pharmpy/issues/733.
> [feature] Add configuration item to give path to NONMEM license file

- docs/custom.css
This fixes UI problems when tables are large.
> [docs] Scroll x-axis overflow of all jupyter outputs

- src/pharmpy/modeling/amd.py
Hi Rikard,
This PR is to create an allometry directory in the amd directory:)
Best regards,
Zhe Huang
> Set the path for allometry tool in amd

- src/pharmpy/datainfo.py
- src/pharmpy/model.py
- src/pharmpy/modeling/data.py
- src/pharmpy/plugins/nonmem/dataset.py
- src/pharmpy/plugins/nonmem/model.py
- tests/modeling/test_data_funcs.py
This fixes some issues regarding dataset comparisons happening when running the resmod tool. Might fix #703.
> [fix] Fix dataset datainfo datatype synchronization

- src/pharmpy/reporting/conf.py
- src/pharmpy/reporting/custom.css
- src/pharmpy/tools/estmethod/report.rst
> [fix] Improve HTML report

- src/pharmpy/tools/resmod/tool.py
Hi Rikard,
This PR is to find the correct location of the model parameters from the result dataframe during the iterations.
Best regards,
Zhe Huang
> Find correct location of model parameter in resmod result

- src/pharmpy/plugins/nonmem/records/code_record.py
- tests/modeling/test_eta_additions.py
> :warning: Needs squash or commit editing
@rikardn Ready for review.
> [fix] Make `add_iov` and `remove_iov` work with case statements

- src/pharmpy/modeling/amd.py
- src/pharmpy/tools/resmod/tool.py
Hi Rikard,
This PR is to fix the wrong start model for each iteration (it always used the first start model as the input model for each iteration so that it can not really do the iterations and generated the wrong best model code) and remove unnecessary iterations in amd. Now the resmod tool can work again:)
Best regards,
Zhe Huang
> Resmod Iteration

- src/pharmpy/plugins/nonmem/model.py
Hi Rikard,
This PR is to make resmod part in amd run:)
Best regards,
Zhe Huang
> Add dummy statements for empty line node in start model

- src/pharmpy/lock.py
- tests/test_lock.py
> [fix/feature] Fix shared process-level lock implementation and allow reentrant locking

- src/pharmpy/tools/common.py
- src/pharmpy/tools/iovsearch/__init__.py
- src/pharmpy/tools/iovsearch/tool.py
- src/pharmpy/tools/rankfuncs.py
- tests/integration/test_iovsearch.py
> [feature] IOV-search tool

- src/pharmpy/modeling/amd.py
Hi Rikard,
This PR is based on our discussion this morning. There are some things that can be improved in the future.
- I think the allometry tool is under construction so I didn't combine allometry results in amd.
- We may need to implement the occasion in datainfo(maybe add a descriptor?) so that when the occasion is none, we can try to find a column for iovsearch which is similar to our strategy for allometry.
Best regard,
Zhe Huang
> Add allometric variable and combine iov tool in amd

- src/pharmpy/modeling/amd.py
- src/pharmpy/tools/amd/funcs.py
- tests/tools/test_start_model.py
Hi Rikard,
This PR is to create a basic datainfo when the user does not provide a datainfo file as input.
Best regards,
Zhe Huang
> Create default datainfo when no datainfo file given(fixes #709)

- docs/covsearch.rst
> [docs] Update, improve, and fix COVsearch docs

- src/pharmpy/tools/iivsearch/algorithms.py
- tests/tools/test_iivsearch.py
> [fix] Handle dummy ETAs in computation of candidate model description in iivsearch

- CHANGELOG.rst
- docs/contribute.rst
- docs/covsearch.rst
- docs/data.rst
- docs/design.rst
- docs/iovsearch.rst
- docs/modeling.rst
- setup.py
- src/pharmpy/__init__.py
> [docs] Some proofreading before the big release!

- src/pharmpy/modeling/remove_iov.py
- src/pharmpy/plugins/nonmem/records/code_record.py
- src/pharmpy/plugins/nonmem/records/omega_record.py
- tests/modeling/test_modeling.py
- tests/testdata/nonmem/models/fviii6.mod
- tests/testdata/nonmem/models/fviii6.prn
> [fix] Make NONMEM `update_source` work with non-trivial IF blocks and fix IOV ETAs discovery in `remove_iov`.

- src/pharmpy/workflows/dispatchers/local_dask.py
- src/pharmpy/workflows/execute.py
- src/pharmpy/workflows/optimize.py
This follows advice found at:
- https://docs.dask.org/en/stable/optimize.html (in particular, the point about using `fuse`)
- https://github.com/dask/distributed/issues/5498#issuecomment-962172751
> [perf] Optimize workflow task graphs

- docs/resmod.rst
Hi Rikard,
This PR is to explain we avoid power+combined error in the resmod. 
Best regards,
Zhe
> Explain the skip strategy of resmod (fixes #938)

- src/pharmpy/expressions.py
- src/pharmpy/modeling/allometry.py
- src/pharmpy/modeling/covariate_effect.py
- src/pharmpy/modeling/error.py
- src/pharmpy/modeling/eta_additions.py
- src/pharmpy/modeling/evaluation.py
- src/pharmpy/modeling/odes.py
- src/pharmpy/modeling/power_on_ruv.py
- src/pharmpy/modeling/results.py
- src/pharmpy/plugins/nonmem/advan.py
- src/pharmpy/random_variables.py
- src/pharmpy/statements.py
- src/pharmpy/utils.py
- tests/modeling/test_modeling.py
- tests/nonmem/test_des.py
> @rikardn Ready to MERGE
The goal is to fix the following issues:
> [fix] Correctly handle parameter discovery in `add_allometry`

- src/pharmpy/modeling/eta_additions.py
- src/pharmpy/tools/run.py
- src/pharmpy/tools/run_amd.py
- tests/integration/test_amd.py
> [fix] Gracefully handle empty inputs to requested subtools in `run_amd` by skipping them

- src/pharmpy/tools/ruvsearch/tool.py
- tests/integration/test_ruvsearch.py
Hi Rikard,
Sorry I forgot we use None as default for ` skip`, I just correct it and add a test for it.
Best regards,
Zhe
> Correct input checking in ruvsearch

- src/pharmpy/tools/allometry/tool.py
> [fix] Return input model in allometry tool if allometry model fails

- src/pharmpy/math.py
- src/pharmpy/model/random_variables.py
- src/pharmpy/model/statements.py
- src/pharmpy/plugins/nonmem/advan.py
Since #1029 is waiting for RVs refactoring, I am merging these independent changes through a shorter path.
> [fix/perf/refactor] A bunch of needed changes identified while working on #1029

- docs/contribute.rst
Hi,
I accidentally find the tox code in Contribute needs to be updated.
> Update tox code in Contribute

- tests/tools/test_amd.py
This reverts commit b87752f01009c6403c39f7a89dfa787090988db3.
> Revert "Fix run_amd unit test failure on Windows"

- src/pharmpy/plugins/nonmem/update.py
- tests/nonmem/test_nonmem_model.py
This solves part of #1139 (long IDs get truncated).
> Add format option to TABLE if ID > 99999

- src/pharmpy/tools/allometry/tool.py
- src/pharmpy/tools/amd/run.py
- tests/tools/test_amd.py
> [feature] Error and warn early on invalid or missing allometric_variable in `run_amd`

- src/pharmpy/internals/fs/tmp.py
- src/pharmpy/workflows/dispatchers/local_dask.py
> [fix] Ignore dask-worker-space cleanup errors on Windows in dispatcher

- src/pharmpy/internals/code_generator.py
- src/pharmpy/plugins/nlmixr/error_model.py
- src/pharmpy/plugins/nlmixr/ini.py
- src/pharmpy/plugins/nlmixr/model.py
- src/pharmpy/plugins/nlmixr/model_block.py
- src/pharmpy/plugins/nlmixr/sanity_checks.py
Update to nlmixr conversion tool for greater error model handling and handling of more limitations
> Update to nlmixr conversion tool

- src/pharmpy/plugins/nlmixr/ini.py
- src/pharmpy/plugins/nlmixr/model_block.py
- src/pharmpy/plugins/rxode/__init__.py
- src/pharmpy/plugins/rxode/model.py
- tests/plugins/test_plugins.py
Contains a new plugin for conversion to RxODE format with the possibility of running RxODE from pharmpy. Rebased pull request #1663 for easier merging and tracking.
> RxODE converter

- src/pharmpy/model/statements.py
- src/pharmpy/plugins/nlmixr/model.py
- src/pharmpy/plugins/nlmixr/model_block.py
- src/pharmpy/plugins/nonmem/advan.py
- src/pharmpy/plugins/nonmem/parsing.py
Should solve issue  #1568 (There seem to have been a duplication with issue #1569)
> Correction of ODE parsing and $DES assignment statements

- src/pharmpy/model/statements.py
- src/pharmpy/plugins/nlmixr/error_model.py
- src/pharmpy/plugins/nlmixr/ini.py
- src/pharmpy/plugins/nlmixr/model.py
- src/pharmpy/plugins/nlmixr/model_block.py
- src/pharmpy/plugins/nonmem/advan.py
- src/pharmpy/plugins/rxode/model.py
Fixed issue with get_bioavailability not working as intended. It was mainly due to:
- When comparing two compartments, bioavailability was not taken into account and hence nodes were not updated as wanted when setting the bioavailability
- When setting dose/bioavailability/alag, the "comp" variable used was not updated and hence did not match the nodes in the nx graph. Added function find_compartment to the CompartmentalSystemBuilder class to avoid building the compartment system each time a compartment is needed. Please let me know if this should be done in some other way
Also included some updates to the conversion tool such as
- Bioavailability conversion
- Further developed error model
- Added support for sigma correlation in RxODE conversion
- Fixed incorrect handling of parameter …
> Bioavailability fixes and updates to conversion tool

- src/pharmpy/plugins/nlmixr/__init__.py
- src/pharmpy/plugins/nlmixr/error_model.py
- src/pharmpy/plugins/nlmixr/model.py
- src/pharmpy/plugins/nlmixr/model_block.py
- src/pharmpy/plugins/rxode/__init__.py
- src/pharmpy/plugins/rxode/model.py
- tests/plugins/test_nlmixr.py
- tests/plugins/test_rxode.py
- Unit tests for nlmixr/rxode
- ability to compare models
- Structural reworked validation workflow
- fixes/updates to bioavailability and error model
> Conversion tool update

- src/pharmpy/modeling/__init__.py
- src/pharmpy/modeling/pd.py
- tests/modeling/test_pd.py
Added a function for direct PD effects. #1740
> Add direct PD effect function

- src/pharmpy/model/external/nlmixr/error_model.py
- src/pharmpy/model/external/nlmixr/model.py
- src/pharmpy/model/external/nlmixr/model_block.py
- src/pharmpy/model/external/nlmixr/sanity_checks.py
- src/pharmpy/model/external/rxode/model.py
- src/pharmpy/tools/external/nlmixr/run.py
- tests/external/test_nlmixr.py
Update to error model capable of extracting more appropriate error terms for additive and proportional errors. More error terms are allowed to be converted. ETA conversion to nlmixr has also been reworked, but with the same function.
> Update to nlmixr2/Rxode2 conversion tool

- src/pharmpy/modeling/__init__.py
- src/pharmpy/modeling/pd.py
- tests/modeling/test_pd.py
Added an effect compartment model.
#1741
> Add effect compartment model

- src/pharmpy/tools/structsearch/pkpd.py
- src/pharmpy/tools/structsearch/tool.py
- tests/tools/test_structsearch.py
> Create PKPD workflow

- src/pharmpy/model/estimation.py
- src/pharmpy/model/external/nonmem/update.py
- src/pharmpy/modeling/estimation_steps.py
- tests/modeling/test_estimation_steps.py
- tests/nonmem/test_nonmem_model.py
Currently allows for three choices for parameter uncertainty estimation: robust sandwich matrix, cross-product gradient matrix, and the observed Fisher information matrix
> Feature: choose covariance method

- src/pharmpy/modeling/pd.py
- tests/modeling/test_pd.py
The step model in modeling/pd.py was corrected.
Edited also the docstring.
> Make changes to effect functions in modeling/pd.py.

- src/pharmpy/model/statements.py
- tests/model/test_statements.py
Add user warning in statements.py. Added a user warning when trying to print model.statements.
#1811
> Add user warning when printing model.statements fails.

- src/pharmpy/model/external/nonmem/update.py
- src/pharmpy/model/statements.py
- src/pharmpy/modeling/common.py
- src/pharmpy/modeling/data.py
- src/pharmpy/modeling/expressions.py
- src/pharmpy/modeling/odes.py
- tests/model/test_statements.py
- tests/tools/test_start_model.py
Changed CompartmentalSystem.dosing_compartment to tuple allowing for multiple dose compartments
> Multiple dose compartment

- src/pharmpy/tools/structsearch/tool.py
- tests/integration/test_structsearch.py
Remove create_pk_model from run_pkpd in structsearch. This will done outside of the structsearch tool.
> Remove create_pk_model in run_pkpd in structsearch

- src/pharmpy/model/external/nonmem/update.py
- src/pharmpy/modeling/__init__.py
- src/pharmpy/modeling/odes.py
Possibility of adding bioavailability using a new parameter or simply a number. When transforming the model, bioavailability will move with the dose.
Also fixed to remove lag time when adding transit compartments
> Add bioavailability statement to model

- src/pharmpy/tools/iivsearch/algorithms.py
- src/pharmpy/tools/iivsearch/tool.py
- tests/integration/test_iivsearch.py
- tests/tools/test_iivsearch.py
Add option in iivsearch to keep iivs for specified parameters. The iivs of these parameters will not be removed in `brure_force_number_of_etas`.
> Add function to keep iivs in iivsearch

- src/pharmpy/tools/estmethod/algorithms.py
- src/pharmpy/tools/estmethod/tool.py
- tests/integration/test_estmethod.py
- tests/tools/test_estmethod.py
Integration test for the estmethod tool, now with support for also testing covariance methods
> Feature: covariance estmethod integration test

- src/pharmpy/modeling/expressions.py
- src/pharmpy/modeling/pd.py
- src/pharmpy/tools/structsearch/pkpd.py
- src/pharmpy/tools/structsearch/tool.py
- tests/integration/test_structsearch.py
- tests/modeling/test_expressions.py
- tests/modeling/test_pd.py
- tests/tools/test_structsearch.py
Updates to pkpd models and structsearch tool.
> Update structsearch tool and pkpd models

- src/pharmpy/model/model.py
- src/pharmpy/modeling/basic_models.py
- tests/modeling/test_basic_models.py
Fix database issue in `create_basic_pk_model`. Before it was not possible to import certain datasets.
> Fix dataset issue in create basic pk model

- src/pharmpy/modeling/basic_models.py
Remove `value_type` from `Model.create()` in `create_basic_pk_model`
> Remove value_type from Model.create()

- src/pharmpy/modeling/pd.py
- src/pharmpy/tools/structsearch/pkpd.py
- tests/integration/test_structsearch.py
- tests/modeling/test_pd.py
- tests/tools/test_structsearch.py
> Make changes to PD models

- src/pharmpy/model/model.py
Changed `datainfo=None` to `datainfo=DataInfo()` in `Model.create()`.
> Change datainfo in Model.create()

- src/pharmpy/tools/iovsearch/tool.py
- tests/integration/test_iovsearch.py
- tests/tools/test_iovsearch.py
Ignore fixed iivs in iovsearch.
> Ignore fixed parameters in IOVSearch

- src/pharmpy/tools/structsearch/pkpd.py
I changed the parameter name from "S" to "slope" but forgot to do so in structsearch/pkpd.py. Has been fixed now.
> Change S to slope

- docs/projects.rst
This was implemented in https://github.com/pharmpy/pharmpy/pull/1304 and https://github.com/pharmpy/pharmpy/commit/66913eafcbf89f6568852c9fbaf155446bd86da5.
> Remove `LALR(1)` project from `projects.rst`

- src/pharmpy/tools/mfl/feature/covariate.py
- tests/tools/test_mfl.py
Add `@PK` and `@PD` to mfl for COVSearch.
> Add @PK and @PD to mfl

- src/pharmpy/model/external/nonmem/parsing.py
- tests/nonmem/test_parser.py
Change nonmem parsing for multiple DVs in `convert_dvs` in `parse_model`.
> Modify nonmem parsing for multiple DVs

- src/pharmpy/tools/estmethod/algorithms.py
- tests/integration/test_estmethod.py
* Modified _create_base_model to handle both evaluation and estimation settings for covariance.
* Updated tests to reflect new behavior.
> Add cov argument to _create_description in algorithms (fixes #1898)

- src/pharmpy/tools/ruvsearch/tool.py
When running RUVsearch, the input model will be checked to see if it has a proportional error model. If it does, then the RUVsearch will move on just as before. If it does not however, a proportional error model will be set and the the model will be re-fitted (in order to obtain new CWRES values) and then the RUVsearch carry on as before (with the proportional error model as input model)
As a final step, the input model is compared to the best resulting model from the search to make sure that an improvement has been made. This effects the cases where the input model was reset to a proportional error model.
> Automatically reset model to proportional if needed in RUVsearch

- src/pharmpy/tools/modelsearch/tool.py
Update description of base model with all features added instead of only last one.
> Change mistaken "=" to "+=" for features of base model.

- docs/tools.rst
- src/pharmpy/modeling/parameter_variability.py
- src/pharmpy/modeling/pd.py
- src/pharmpy/tools/mfl/feature/direct_effect.py
- src/pharmpy/tools/mfl/feature/effect_comp.py
- src/pharmpy/tools/mfl/feature/indirect_effect.py
- src/pharmpy/tools/mfl/grammar.py
- src/pharmpy/tools/mfl/helpers.py
- src/pharmpy/tools/mfl/interpreter.py
- src/pharmpy/tools/mfl/statement/feature/direct_effect.py
- src/pharmpy/tools/mfl/statement/feature/effect_comp.py
- src/pharmpy/tools/mfl/statement/feature/indirect_effect.py
- src/pharmpy/tools/structsearch/pkpd.py
- src/pharmpy/tools/structsearch/tool.py
- tests/modeling/test_expressions.py
- tests/modeling/test_pd.py
- tests/tools/test_mfl.py
- tests/tools/test_structsearch.py
Add MFL for structsearch for pkpd models.
> Add MFL for structsearch for pkpd models

- src/pharmpy/reporting/reporting.py
Use context manager instead of manually opening and closing
> Use context manager

- src/pharmpy/tools/amd/run.py
After the MFL update, search spaces need to be explicit and so the defualt searchspaces within AMD have been updated to match this new way of thinking
> Correct default search space in AMD

- src/pharmpy/model/external/nonmem/records/theta_record.py
- tests/nonmem/records/test_theta.py
- tests/nonmem/test_nonmem_model.py
Changes made:
Lower bounds of thetas will now be updated when using `model.update_source()`.
> Update lower bounds for thetas

- src/pharmpy/model/model.py
- src/pharmpy/tools/external/nonmem/results.py
- src/pharmpy/tools/external/nonmem/results_file.py
* Clarify variable names
* Fix grammar/typos
> Refactor `tools/external/nonmem/results.py`

- src/pharmpy/modeling/pd.py
Change docstrings of PD models from additive effect to proportional effect.
> Fix docstrings for PD models. Additive -> Proportional

- src/pharmpy/tools/amd/run.py
- src/pharmpy/tools/mfl/filter.py
Enable search_space for structsearch in AMD.
#2112
> Enable search_space for structsearch in AMD

- docs/amd.rst
- docs/structsearch.rst
- src/pharmpy/tools/amd/run.py
- src/pharmpy/tools/structsearch/tool.py
- tests/integration/test_ruvsearch.py
- tests/integration/test_structsearch.py
- tests/tools/test_structsearch.py
Update documentation for drug metabolite models within structsearch. Some updates to the general structure of the entire tool as well.
> Update structsearch documentation

- src/pharmpy/modeling/tmdd.py
- tests/modeling/test_tmdd.py
Changes to Wagner and QSS TMDD models after discussion.
> Changes to Wagner and QSS TMDD models

- src/pharmpy/tools/amd/run.py
- src/pharmpy/tools/structsearch/tmdd.py
- src/pharmpy/tools/structsearch/tool.py
Add structsearch for TMDD models in AMD tool.
> Add structsearch for TMMD in AMD

- src/pharmpy/modeling/tmdd.py
> Change LCfree to LAfree

- docs/amd.rst
- src/pharmpy/tools/amd/run.py
Changes to the default search spaces (please see issue #2117)
> Remove all non-linear eliminations from default search spaces

- src/pharmpy/tools/amd/run.py
- src/pharmpy/tools/run.py
- src/pharmpy/tools/structsearch/tool.py
- tests/integration/test_structsearch.py
Fix problem in structsearch with optional input model.
> Fix structsearch

- src/pharmpy/model/estimation.py
- tests/model/test_model.py
Fix issue with frozenmapping.
Related to issue #2096
> Fix frozenmapping issue

- src/pharmpy/tools/structsearch/tmdd.py
- src/pharmpy/tools/structsearch/tool.py
- tests/tools/test_structsearch.py
Fix some issues in structsearch for TMDD models.
> Fix issues in structsearch for tmdd models

- src/pharmpy/tools/structsearch/tool.py
add `update_initial_estimates` to structsearch for TMDD.
> Add update_initial_estimates to structsearch tmdd

- src/pharmpy/modeling/blq.py
Add information about the different methods and what is changed in the model/dataset.
> Extend docstring for transform_blq

- src/pharmpy/internals/expr/parse.py
Allow sympy.sympify('N'). This raised an error before.
> Allow sympy.sympify('N')

- src/pharmpy/tools/amd/run.py
- src/pharmpy/tools/common.py
- src/pharmpy/tools/modelsearch/tool.py
- src/pharmpy/tools/run.py
- src/pharmpy/tools/structsearch/tool.py
- tests/tools/test_run.py
Implement user specified strictness filtering.
Implemented arguments are:
- minimization_successful
-  rounding_errors
- maxeval_exceeded
- sigdigs (significant_digits)
- RSE (relatove standard errors)
Implemented in 
- structsearch
- modelsearch
> Implement user specified strictness filtering #2053

- src/pharmpy/tools/external/nonmem/results.py
- src/pharmpy/tools/external/nonmem/run.py
- src/pharmpy/workflows/results.py
- tests/nonmem/test_modelfit_results.py
- tests/testdata/nonmem/pheno.grd
Add attributes `gradients`, `gradients_iterations`, `warnings` and `covstep_successful` to `ModelfitResults`.
#2186 , #2187
> Add attributes to ModelfitResults

- docs/structsearch.rst
- src/pharmpy/modeling/expressions.py
- tests/modeling/test_expressions.py
Extract pk parameters for drug metabolite if there exist a flow between the compartment connected to the drug (dvid=1) and the metabolite (dvid=2)
> Correct extraction of pk parameters for drug metabolite

- src/pharmpy/tools/amd/run.py
Select models with mixed-FO-MM elimination after modelsearch for TMDD models.
> Only use models with mixed-FO-MM elimination

- src/pharmpy/modeling/expressions.py
Should fix failing unit test for test_get_pk_parameters_metabolite
> Update metabolite pk param extraction to use function for amounts

- src/pharmpy/tools/external/nonmem/results.py
- src/pharmpy/tools/run.py
- tests/tools/test_run.py
Add two more strictness criteria:
- has_zero_gradient
- estimate_near_boundary
> Add strictness criteria has_zero_gradient and estimate_near_boundary

- src/pharmpy/tools/mfl/feature/direct_effect.py
- src/pharmpy/tools/mfl/feature/effect_comp.py
- src/pharmpy/tools/mfl/feature/indirect_effect.py
- src/pharmpy/tools/structsearch/pkpd.py
Change so that function extractions for PKPD models works similarly to other attributes
> Change so that mfl for PKPD function return function instead of model

- src/pharmpy/modeling/__init__.py
- src/pharmpy/modeling/pd.py
- src/pharmpy/tools/structsearch/pkpd.py
- tests/model/test_statements.py
- tests/modeling/test_expressions.py
- tests/modeling/test_pd.py
Add function `create_baseline_effect`.
Remove baseline option from `set_direct_effect`and `add_effect_compartment`.
Replace baseline function in structsearch.
> Add create_baseline_effect

- src/pharmpy/model/statements.py
- src/pharmpy/modeling/odes.py
- src/pharmpy/modeling/tmdd.py
- tests/modeling/test_odes.py
- tests/modeling/test_tmdd.py
Fix allometry for TMDD models.
> Fix allometry for TMDD models

- docs/structsearch.rst
- docs/tools.rst
Add documentation for structsearch for TMDD models
> Add documentation for structsearch for TMDD

- src/pharmpy/modeling/odes.py
- src/pharmpy/modeling/tmdd.py
- src/pharmpy/tools/amd/run.py
- src/pharmpy/tools/structsearch/tmdd.py
- src/pharmpy/tools/structsearch/tool.py
- tests/modeling/test_tmdd.py
- tests/tools/test_structsearch.py
Update TMDD models:
- Update ODE system for MMAPP models
- Update parameter name "POP_VC". Does not crash anymore when "POP_VC" does not exists in parameter estimates.
- Update initial estimate for POP_KM
> Update TMDD models

- src/pharmpy/tools/structsearch/tool.py
Add strictness to drug-metabolite in structsearch
> Add strictness to drug-metabolite

- src/pharmpy/tools/run.py
Add docstring for is_strictness_fulfilled
> Add docstring for is_strictness_fulfilled

- src/pharmpy/modeling/tmdd.py
- src/pharmpy/tools/structsearch/tmdd.py
- tests/modeling/test_odes.py
- tests/modeling/test_tmdd.py
> Make fixes to TMDD models

- src/pharmpy/tools/common.py
Add base model to res_models. That way all models appear in `results.models`.
> Add base_model to res_models

- src/pharmpy/modeling/allometry.py
- src/pharmpy/modeling/covariate_effect.py
- src/pharmpy/tools/amd/run.py
> Revert "Avoid removing allometry scaling in AMD"

- src/pharmpy/modeling/tmdd.py
- tests/modeling/test_odes.py
- tests/modeling/test_tmdd.py
Hopefully last changes to MMAPP models.
> Fixed to MMAPP models

- src/pharmpy/modeling/common.py
Update documentation for `filter_dataset` to make it clearer how it is used.
> Update documentation for filter_dataset

- src/pharmpy/tools/amd/run.py
- src/pharmpy/tools/common.py
- src/pharmpy/tools/covsearch/tool.py
- src/pharmpy/tools/iivsearch/tool.py
- src/pharmpy/tools/iovsearch/tool.py
- src/pharmpy/tools/modelsearch/tool.py
- src/pharmpy/tools/run.py
- src/pharmpy/tools/ruvsearch/tool.py
- src/pharmpy/tools/structsearch/tool.py
- tests/tools/test_run.py
Changes to strictness:
- do not allow operators such as &, | and ^
- change default sigdigs to >= 0.1
> Update is strictness fulfilled

- src/pharmpy/model/external/nlmixr/model.py
- src/pharmpy/tools/external/nlmixr/run.py
Fixed issue with file path when running models in R.
Also fixes conversion issue by changing A_CENTRAL(t) variables to A_CENTRAL due to function naming (A_CENTRAL(t)) not being supported in nlmixr/rxode
> File path for windows in nlmixr/rxode

- src/pharmpy/tools/amd/run.py
Make changes to modelsearch in structsearch for TMDD in AMD.
> Fix modelsearch in structsearch for TMMD in AMD

- src/pharmpy/tools/external/nonmem/results.py
- src/pharmpy/tools/run.py
- tests/tools/test_run.py
Add strictness for different parameter types (thetas, omegas and sigmas).
Related to #2290
> Add strictness for different parameter types

- src/pharmpy/tools/amd/run.py
- src/pharmpy/tools/modelfit/tool.py
- src/pharmpy/tools/structsearch/pkpd.py
- src/pharmpy/tools/structsearch/tmdd.py
- src/pharmpy/tools/structsearch/tool.py
- tests/tools/test_structsearch.py
Implement ModelEntry in structsearch for tmdd and pkpd.
> Implement ModelEntry in structsearch

- docs/tools.rst
update strictness documentation
> update strictness documentation

- src/pharmpy/model/external/nonmem/records/code_record.py
- src/pharmpy/model/external/nonmem/records/grammars/code_record.lark
- src/pharmpy/modeling/tmdd.py
- src/pharmpy/tools/amd/run.py
- src/pharmpy/tools/structsearch/tmdd.py
- src/pharmpy/tools/structsearch/tool.py
- tests/modeling/test_error.py
- tests/modeling/test_metabolite.py
- tests/modeling/test_tmdd.py
- tests/tools/test_structsearch.py
> TMDD for multiple DVs

- src/pharmpy/tools/amd/run.py
Add dv_types to structsearch for TMDD
> Add dv_types to structsearch for TMDD in AMD

- src/pharmpy/modeling/tmdd.py
Change sign in QSS models for target DV.
> Change sign in QSS models

- src/pharmpy/model/external/nlmixr/model_block.py
Should fix issues with zero order- and sequential first order zero order absorption models.
> Add variable for rate/dur in nlmixr/rxode conversion

- src/pharmpy/tools/structsearch/tool.py
- tests/tools/test_structsearch.py
> Validate structsearch input

- src/pharmpy/modeling/tmdd.py
- src/pharmpy/tools/structsearch/tool.py
- tests/modeling/test_tmdd.py
- tests/tools/test_structsearch.py
- Fix bug in `validate_input` in structsearch for TMDD models.
- Add more tests for input validation and validation of `dv_types`
> Fix input validation tmdd

- src/pharmpy/modeling/common.py
- src/pharmpy/modeling/estimation_steps.py
- src/pharmpy/modeling/expressions.py
- src/pharmpy/modeling/odes.py
- src/pharmpy/modeling/results.py
Add `Literal` type hints to modeling functions
> Add Literal type hints modeling functions

- src/pharmpy/tools/amd/run.py
Modelsearch default search space for TMDD models with MM and MIX-FO-MM
> Modelsearch default search space for TMDD

- docs/amd.rst
- docs/estmethod.rst
- src/pharmpy/model/estimation.py
Add documentation for `parameter_uncertainty_method` in AMD tool.
> Add documentation for parameter_uncertainty_method

- docs/amd.rst
- src/pharmpy/tools/amd/run.py
Change naming of
SIRIAC - all
SIRIACIR - retries
and add three new methods
SIR, SRI and RSI
Also made updates to the documentation for AMD to make it a bit clearer on how the different modeltypes affect the different strategies. Comments are greatly appreciated :)
> Change naming of strategies and add SIR, SRI, RSI

- src/pharmpy/tools/amd/run.py
- src/pharmpy/tools/iivsearch/tool.py
- src/pharmpy/workflows/model_database/baseclass.py
- src/pharmpy/workflows/model_database/local_directory.py
Also removes usage of `Model.modelfit_results` in model database.
> Avoid model reparsing in AMD

- src/pharmpy/model/external/nonmem/model.py
- src/pharmpy/model/external/nonmem/parsing.py
- src/pharmpy/model/external/nonmem/update.py
- src/pharmpy/tools/amd/run.py
- src/pharmpy/tools/external/nonmem/results.py
- tests/integration/test_amd.py
- tests/modeling/test_estimation_steps.py
> Fix $DESIGN

- src/pharmpy/model/external/nonmem/update.py
- tests/modeling/test_estimation_steps.py
Before estimation was not updated when old and new parameter uncertainty were not None. Now this case has been implemented as well.
> Fix update parameter uncertainty method

- requirements.txt
> Revert "Bump dask from 2024.2.0 to 2024.2.1"

- src/pharmpy/tools/amd/run.py
> Fix keep clearance for iivsearch in AMD

- src/pharmpy/tools/amd/run.py
- src/pharmpy/tools/structsearch/tool.py
- Make initial estimates for PKPD models mandatory in AMD and structsearch
- Add default covsearch search space for PKPD models
> Make inits for pkpd models mandatory

- src/pharmpy/modeling/plots.py
Add example plot for eta distribution
> Add example eta distribution plot

- src/pharmpy/tools/__init__.py
- src/pharmpy/tools/external/nonmem/__init__.py
- src/pharmpy/tools/external/nonmem/results.py
- src/pharmpy/tools/external/nonmem/run.py
- src/pharmpy/tools/run.py
- src/pharmpy/tools/simulation/__init__.py
- src/pharmpy/tools/simulation/tool.py
- src/pharmpy/workflows/__init__.py
- src/pharmpy/workflows/model_entry.py
- src/pharmpy/workflows/results.py
- tests/integration/test_simulation.py
- Create a simulation tool
- create `SimulationResults` object
- Create attribute `simulation_results` for `ModelEntry`
> Create a simulation tool

- src/pharmpy/modeling/results.py
- src/pharmpy/tools/allometry/report.rst
- src/pharmpy/tools/amd/results.py
- src/pharmpy/tools/amd/run.py
- src/pharmpy/tools/common.py
- src/pharmpy/tools/covsearch/report.rst
- src/pharmpy/tools/covsearch/results.py
- src/pharmpy/tools/iivsearch/report.rst
- src/pharmpy/tools/iivsearch/tool.py
- src/pharmpy/tools/iovsearch/report.rst
- src/pharmpy/tools/iovsearch/tool.py
- src/pharmpy/tools/modelsearch/report.rst
- src/pharmpy/tools/modelsearch/tool.py
- src/pharmpy/tools/retries/report.rst
- src/pharmpy/tools/retries/tool.py
- src/pharmpy/tools/ruvsearch/report.rst
- src/pharmpy/tools/ruvsearch/results.py
- src/pharmpy/tools/ruvsearch/tool.py
- src/pharmpy/tools/structsearch/report.rst
- src/pharmpy/tools/structsearch/tool.py
Create report for the final model of each AMD subtool.
> Add report for final models of each subtool

- src/pharmpy/modeling/data.py
- src/pharmpy/modeling/plots.py
- src/pharmpy/tools/amd/report.rst
- src/pharmpy/tools/amd/results.py
- src/pharmpy/tools/amd/run.py
> Add VPC plot to AMD results report

- src/pharmpy/tools/iovsearch/tool.py
- tests/tools/test_iovsearch.py
> Allow list of lists of parameters in iovsearch (#2807)

- src/pharmpy/model/external/nonmem/records/code_record.py
- src/pharmpy/model/statements.py
- src/pharmpy/modeling/allometry.py
- src/pharmpy/modeling/common.py
- src/pharmpy/modeling/covariate_effect.py
- src/pharmpy/modeling/expressions.py
- src/pharmpy/tools/common.py
- tests/modeling/test_covariate_effect.py
- tests/nonmem/records/test_code.py
- tests/workflows/test_hashing.py
- Removal of the automatic addition of "ELSE" statements in if statements where it is not explicitely stated
- Correct expansion of exponential covariate effects when combined with other exponential terms
- More test cases for get_covariate_effects
> Expand logic for covariate effect extraction

- src/pharmpy/tools/ruvsearch/tool.py
- tests/tools/test_ruvsearch.py
Now all columns are filtered by DVID in `_create_dataset` in RUVSearch.
> Fix dataset filtering ruvsearch

- src/pharmpy/tools/iivsearch/algorithms.py
- src/pharmpy/tools/iivsearch/tool.py
Models should not be able to be chosen in a step if they fail the given strictness criteria
> Apply strictness in each step in bottom_up_stepwise IIVSearch

- src/pharmpy/modeling/__init__.py
- src/pharmpy/modeling/estimation_steps.py
- tests/modeling/test_estimation_steps.py
Helper functions for adding and removing which derivatives are to be extracted when running the model
> Function for adding and removing derivatives

- src/pharmpy/model/external/nonmem/parsing.py
- tests/nonmem/test_nonmem_model.py
Add support for parsing of NONMEM derivatives written within verbatim code
> Complete parsing of NONMEM derivatives

- src/pharmpy/tools/structsearch/tool.py
- tests/integration/test_covsearch.py
- tests/integration/test_iivsearch.py
- tests/integration/test_iovsearch.py
- tests/integration/test_modelsearch.py
- tests/integration/test_retries.py
Update failing integration tests after #2982
> Update integration tests after adding input and final model

- docs/drug_metabolite.rst
After previous restructures, the drug metabolite documentation had some descriptions that are no longer accurate. Comments on other changes are more than welcome
> Update drug metabolite documentation

- src/pharmpy/tools/common.py
- src/pharmpy/tools/covsearch/tool.py
- src/pharmpy/tools/ruvsearch/tool.py
Change `store_key` to `store_input_model_entry` and `store_final_model_entry` to get annotations as well.
> Change store_key to store_model_entry

- docs/linearize_tool.rst
- docs/tools.rst
- src/pharmpy/tools/__init__.py
- src/pharmpy/tools/linearize/__init__.py
- src/pharmpy/tools/linearize/results.py
- src/pharmpy/tools/linearize/tool.py
- tests/integration/test_linearize.py
- tests/testdata/nonmem/linearize/linearize_dir1/scm_dir1/derivatives.mod
- tests/tools/test_linearize.py
Updates to and restructure of the linearization procedure.
> Restructure linearize tool

- src/pharmpy/modeling/__init__.py
- src/pharmpy/modeling/common.py
- tests/modeling/test_common.py
Add function `set_description` to change model description.
> Add modeling function set_description

- .devcontainer/devcontainer.json
- MANIFEST.in
This is a first draft that works for me. Includes Python 3.11 and 3.12.
> Add dev container configuration for VS Code

- tox.ini
This improves type checking experience in VS Code.
> Include tests requirements in type-checking `tox` environment
